specVersion: 1.0.0
name: InvArch-subql
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: Data indexing for InvArch network
repository: 'https://github.com/InvArch/InvArch-subql'
schema:
  file: ./schema.graphql
network:
  # Polkadot
  # chainId: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  # endpoint: 'wss://polkadot.api.onfinality.io/public-ws'

  # Brainstorm
  # chainId: '0x7c91172ebbe284db5d1394136958ebdf46f475c1473d206d31895e81d17361b2'
  # endpoint: 'wss://brainstorm.invarch.network'

  # Tinkernet
  chainId: '0xd42e9606a995dfe433dc7955dc2a70f495f350f373daa200098ae84437816ad2'
  # endpoint: 'ws://34.202.164.131:9944'
  endpoint: 'wss://node-6968552592343965696.sz.onfinality.io/ws?apikey=8c65a305-003e-4956-ac74-f9c0a3ec526e'
  # endpoint: 'wss://tinker.invarch.network/'

  # Local Node
  # chainId: '0x27214161c6530755f4da1d5ea71601882045836800431529da6749d90cc8297c'
  # endpoint: 'ws://127.0.0.1:9944'
  # dictionary: 'https://api.subquery.network/sq/subquery/polkadot-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        # - handler: handleBlock
        #   kind: substrate/BlockHandler
        - handler: handleIPSCreated
          kind: substrate/EventHandler
          filter:
            module: inv4
            method: IPSCreated
        - handler: handleAppendedToIPS
          kind: substrate/EventHandler
          filter:
            module: inv4
            method: AppendedToIPS
        - handler: handleRemovedFromIPS
          kind: substrate/EventHandler
          filter:
            module: inv4
            method: RemovedFromIPS
        - handler: handleAllowedReplica
          kind: substrate/EventHandler
          filter:
            module: inv4
            method: AllowedReplica
        - handler: handleDisallowedReplica
          kind: substrate/EventHandler
          filter:
            module: inv4
            method: DisallowedReplica
        - handler: handleMinted
          kind: substrate/EventHandler
          filter:
            module: ipf
            method: Minted
        - handler: handleBurned
          kind: substrate/EventHandler
          filter:
            module: ipf
            method: Burned






        # - handler: handleCall
        #   kind: substrate/CallHandler
